CREATE TYPE "papel_ong" AS ENUM (
  'ADMIN',
  'MEMBRO'
);

CREATE TYPE "status_campanha" AS ENUM (
  'RASCUNHO',
  'ATIVA',
  'ENCERRADA',
  'CANCELADA'
);

CREATE TYPE "forma_pagamento" AS ENUM (
  'PIX',
  'CARTAO'
);

CREATE TYPE "status_doacao" AS ENUM (
  'PENDENTE',
  'CONCLUIDA',
  'FALHOU',
  'CANCELADA'
);

CREATE TABLE "usuarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(120) NOT NULL,
  "email" varchar(180) UNIQUE NOT NULL,
  "senha_hash" varchar(255) NOT NULL,
  "telefone" varchar(20),
  "foto_url" varchar(500),
  "criado_em" timestamp NOT NULL DEFAULT (now()),
  "atualizado_em" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categorias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "descricao" varchar(255)
);

CREATE TABLE "ongs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_id" bigint NOT NULL,
  "nome" varchar(150) NOT NULL,
  "cnpj" varchar(18) UNIQUE,
  "descricao" text NOT NULL,
  "email" varchar(180),
  "telefone" varchar(20),
  "cep" varchar(9) NOT NULL,
  "logradouro" varchar(255) NOT NULL,
  "numero" varchar(20) NOT NULL,
  "complemento" varchar(100),
  "bairro" varchar(100),
  "cidade" varchar(100) NOT NULL,
  "estado" varchar(2) NOT NULL,
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "imagem_url" varchar(500),
  "criado_em" timestamp NOT NULL DEFAULT (now()),
  "atualizado_em" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "usuarios_ongs" (
  "usuario_id" bigint NOT NULL,
  "ong_id" bigint NOT NULL,
  "papel" papel_ong NOT NULL DEFAULT 'MEMBRO',
  "data_vinculo" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "ong_id")
);

CREATE TABLE "campanhas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ong_id" bigint NOT NULL,
  "titulo" varchar(150) NOT NULL,
  "descricao" text NOT NULL,
  "meta" decimal(12,2) NOT NULL,
  "data_inicio" date NOT NULL,
  "data_fim" date,
  "status" status_campanha NOT NULL DEFAULT 'RASCUNHO',
  "imagem_url" varchar(500),
  "criado_em" timestamp NOT NULL DEFAULT (now()),
  "atualizado_em" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "doacoes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL,
  "campanha_id" bigint NOT NULL,
  "valor" decimal(12,2) NOT NULL,
  "forma_pagamento" forma_pagamento NOT NULL,
  "status" status_doacao NOT NULL DEFAULT 'PENDENTE',
  "data_doacao" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "favoritos" (
  "usuario_id" bigint NOT NULL,
  "ong_id" bigint NOT NULL,
  "data_favorito" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "ong_id")
);

ALTER TABLE "ongs" ADD CONSTRAINT "categoria_ong" FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios_ongs" ADD CONSTRAINT "usuario_usuario_ong" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios_ongs" ADD CONSTRAINT "ong_usuario_ong" FOREIGN KEY ("ong_id") REFERENCES "ongs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "campanhas" ADD CONSTRAINT "ong_campanha" FOREIGN KEY ("ong_id") REFERENCES "ongs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "doacoes" ADD CONSTRAINT "usuario_doacao" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "doacoes" ADD CONSTRAINT "campanha_doacao" FOREIGN KEY ("campanha_id") REFERENCES "campanhas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favoritos" ADD CONSTRAINT "usuario_favorito" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favoritos" ADD CONSTRAINT "ong_favorito" FOREIGN KEY ("ong_id") REFERENCES "ongs" ("id") DEFERRABLE INITIALLY IMMEDIATE;
