spring.application.name=NOME_BANCO

spring.datasource.url=URL_BANCO
spring.datasource.username=USUARIO_BANCO
spring.datasource.password=SENHA_BANCO
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true